# Generated by Django 3.1.2 on 2020-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
